name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  macos:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - run: swift build -c release
      - run: swift test

  linux:
    runs-on: ubuntu-latest
    container: swift:6.1
    steps:
      - uses: actions/checkout@v4
      - run: swift build -c release
      - run: swift test

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.1-release
          tag: 6.1-RELEASE
      - run: swift build -c release
      - run: swift test
